### ISSUE TITLE
errors when running with Ruby 3.x

### ISSUE THREAD

**Issue by pirafrank** [pirafrank/fpiracom#13]
```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Configuration file: /workspace/fpiracom/_config.yml
            Source: /workspace/fpiracom
       Destination: /workspace/fpiracom/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
                    done in 3.781 seconds.
 Auto-regeneration: enabled for '/workspace/fpiracom'
                    ------------------------------------------------
      Jekyll 4.2.1   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/home/gitpod/.rvm/gems/ruby-3.1.2/gems/jekyll-4.2.1/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/jekyll-4.2.1/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:179:in `require_relative'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:179:in `setup'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:100:in `process'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `each'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/bin/jekyll:25:in `load'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/bin/jekyll:25:in `<main>'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/bin/ruby_executable_hooks:22:in `eval'
        from /home/gitpod/.rvm/gems/ruby-3.1.2/bin/ruby_executable_hooks:22:in `<main>'
gitpod /workspace/fpiracom (main) $ ruby --version
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
```

**Comment by pirafrank** [comment]
maybe useful
- https://github.com/rubygems/rubygems/issues/5236
- https://talk.jekyllrb.com/t/load-error-cannot-load-such-file-webrick/5417

**Comment by pirafrank** [comment]
These are actually two issues.

Issue: `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated...`

Fix: `bundle update --bundler`

Issue: `servlet.rb:3:in require': cannot load such file -- webrick (LoadError)`

Fix: add `gem "webrick"` to Gemfile and then run `bundle install`, or just run `bundle add webrick`
